from app.schemas.auth import (
    LoginRequest,
    LogoutRequest,
    MessageResponse,
    PasswordResetConfirm,
    PasswordResetRequest,
    RefreshRequest,
    RegisterRequest,
    TokenPairResponse,
    TokenResponse,
    UserResponse,
    UserUpdateRequest,
)
from app.schemas.master import (
    CategoryBrief,
    MasterDetail,
    MasterListItem,
    MasterProfileCreate,
    MasterProfileUpdate,
    PaginatedResponse,
    PortfolioImageResponse,
    ServiceCreate,
    ServiceResponse,
    ServiceUpdate,
    UserBrief,
)
from app.schemas.booking import (
    BookingCreate,
    BookingDetail,
    BookingListItem,
    BookingResponse,
    BookingStatusUpdate,
    BulkSlotCreate,
    BulkSlotResponse,
    PaymentBrief,
    ServiceBrief,
    TimeSlotCreate,
    TimeSlotResponse,
)
from app.schemas.payment import (
    BalanceResponse,
    PaymentResponse,
    PayoutCreate,
    PayoutResponse,
    TransactionItem,
    WebhookPayload,
)
from app.schemas.chat import (
    ChatRoomResponse,
    MessageBrief,
    MessageCreate,
    MessageResponse as ChatMessageResponse,
)
from app.schemas.review import (
    RatingSummary,
    ReviewCreate,
    ReviewListResponse,
    ReviewReply,
    ReviewResponse,
)
from app.schemas.notification import (
    FcmTokenCreate,
    MarkReadRequest,
    MarkReadResponse,
    NotificationListResponse,
    NotificationResponse,
)
from app.schemas.admin import (
    AdminPayoutUpdate,
    AdminReviewUpdate,
    AdminUserUpdate,
    BookingsStats,
    CategoryCreate,
    CategoryResponse,
    CategoryUpdate,
    DashboardStats,
    RevenueStats,
    TransactionListResponse,
    UsersStats,
    VerificationUpdate,
)

__all__ = [
    # auth
    "RegisterRequest",
    "LoginRequest",
    "TokenResponse",
    "RefreshRequest",
    "TokenPairResponse",
    "LogoutRequest",
    "UserResponse",
    "UserUpdateRequest",
    "MessageResponse",
    "PasswordResetRequest",
    "PasswordResetConfirm",
    # master
    "MasterProfileCreate",
    "MasterProfileUpdate",
    "MasterListItem",
    "MasterDetail",
    "UserBrief",
    "CategoryBrief",
    "ServiceResponse",
    "ServiceCreate",
    "ServiceUpdate",
    "PortfolioImageResponse",
    "PaginatedResponse",
    # booking
    "TimeSlotResponse",
    "TimeSlotCreate",
    "BulkSlotCreate",
    "BulkSlotResponse",
    "BookingCreate",
    "BookingResponse",
    "BookingDetail",
    "BookingStatusUpdate",
    "BookingListItem",
    "ServiceBrief",
    "PaymentBrief",
    # payment
    "PaymentResponse",
    "BalanceResponse",
    "PayoutCreate",
    "PayoutResponse",
    "TransactionItem",
    "WebhookPayload",
    # chat
    "ChatRoomResponse",
    "ChatMessageResponse",
    "MessageBrief",
    "MessageCreate",
    # review
    "ReviewCreate",
    "ReviewResponse",
    "ReviewReply",
    "ReviewListResponse",
    "RatingSummary",
    # notification
    "NotificationResponse",
    "NotificationListResponse",
    "MarkReadRequest",
    "MarkReadResponse",
    "FcmTokenCreate",
    # admin
    "DashboardStats",
    "UsersStats",
    "BookingsStats",
    "RevenueStats",
    "AdminUserUpdate",
    "VerificationUpdate",
    "AdminReviewUpdate",
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryResponse",
    "AdminPayoutUpdate",
    "TransactionListResponse",
]
